match rotary direction to standard rotaryio
adafruit/Adafruit_CircuitPython_seesaw pull request #70
Opened 2021-06-01 19:16 UTC by jfurcean

This makes it so clockwise rotation is positive and counter-clockwise is negative to match the standard `rotaryio` library.

2021-06-01 20:08 UTC, dhalbert requested changes
Thanks for doing this so fast. I vote for negating, because the interpreter will not necessarily optimize the multiplication.

2021-06-01 20:08 UTC, dhalbert commented on adafruit_seesaw/seesaw.py
> +        return struct.unpack(">i", buf)[0] * -1
```suggestion
        return -struct.unpack(">i", buf)[0]
```

2021-06-01 20:08 UTC, dhalbert commented on adafruit_seesaw/seesaw.py
> +        return struct.unpack(">i", buf)[0] * -1
Negating is faster than multiplying.

2021-06-01 20:08 UTC, dhalbert commented on adafruit_seesaw/seesaw.py
> +        return struct.unpack(">i", buf)[0] * -1
```suggestion
        return -struct.unpack(">i", buf)[0]
```

2021-06-01 20:08 UTC, dhalbert commented
Could you add a comment too, to each place, explaining why you're doing the negation?

2021-06-01 20:37 UTC, jfurcean commented
I updated it to use negation instead of multiplication and added comments.

2021-06-10 15:44 UTC, dhalbert commented
@ladyada Did you want to forget about doing this in the library? I think you indicated you would rather just have some products be backwards and change the firmware for future products.

So the question is whether to merge this or just forget it.

2021-06-10 15:45 UTC, closed without merging

2021-06-10 17:22 UTC, ladyada commented
i would like it in the example not the library please!